# https://circleci.com/docs/2.0/language-javascript/
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.8

    working_directory: ~/repo

    steps:
      - checkout

      # download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Test Suite"
          command: yarn test:ci

      - run:
          name: "Linter"
          command: yarn lint:ci

      - store_test_results:
          path: reports/junit

      - store_artifacts:
          path: reports/junit
